import { afterAll, describe, expect, it } from "bun:test"
import { mkdtempSync, rmSync, writeFileSync } from "node:fs"
import { tmpdir } from "node:os"
import { join } from "node:path"
import type { PluginLaunchInput } from "../../contracts/generated/korrid"
import { launch } from "./plugin"

function input(overrides?: PluginLaunchInput["overrides"]): PluginLaunchInput {
  return {
    launcherId: "@korri:retroarch/retroarch",
    launcherKind: "@korri:retroarch/retroarch",
    runtimeId: "@korri:mgba/mgba",
    program: "/program",
    runtimePath: "/core",
    contentPath: "/rom",
    accountRoot: "/account",
    files: { autoconfig: "/autoconfig" },
    overrides,
  }
}

function content(overrides?: PluginLaunchInput["overrides"]): string {
  return launch(input(overrides)).files![0].content
}

const reserved = [
  "cheevos_password", "cheevos_token", "network_cmd_password",
  "netplay_password", "netplay_spectate_password", "kiosk_mode_enable",
  "config_save_on_exit", "menu_driver",
]

describe("RetroArch native configuration", () => {
  it("emits one assignment per key across baseline, typed and repeated raw values", () => {
    const cfg = content({
      settings: { video_driver: "vulkan", audio_volume: -3.5 },
      config: {
        prepend: '# ignored\nvideo_driver = "sdl2"\naudio_volume = -2',
        append: 'video_driver = "glcore"\nvideo_driver = "gl1" # final',
      },
    })
    const keys = cfg.split("\n").filter((line) => line.includes(" = "))
      .map((line) => line.split(" = ")[0])
    expect(new Set(keys).size).toBe(keys.length)
    expect(cfg).toContain('video_driver = "gl1" # final\n')
    expect(cfg).toContain("# generated by Korri\n")
    expect(cfg).toContain("# RetroArch value 2 is L3 + R3.")
    expect(cfg).not.toContain("# ignored")
  })

  it("rejects every reserved key even when a later assignment would hide it", () => {
    for (const key of reserved) {
      expect(() => content({ settings: { [key]: false } })).toThrow(key)
      for (const block of ["prepend", "append"] as const) {
        expect(() => content({ config: { [block]: `${key} = false\n${key} = true` } }))
          .toThrow(key)
      }
      expect(() => content({ settings: { [key]: false }, config: { append: `${key} = true` } }))
        .toThrow(key)
    }
  })

  it("retains raw comments, native values and config key validation rules", () => {
    expect(content({ config: { prepend: '\n #include "not-loaded.cfg"\n Future_key9 = "a#b" # comment\n' } }))
      .toContain('Future_key9 = "a#b" # comment\n')
    for (const line of ["missing", "= value", "bad-key = value", "a b = value", "#skip\n[section]"]) {
      expect(() => content({ config: { append: line } })).toThrow("Invalid RetroArch")
    }
    expect(() => content({ settings: { "bad-key": true } })).toThrow("invalid")
    expect(() => content({ config: { replace: "" } })).toThrow("replace")
    for (const value of [NaN, Infinity, -Infinity]) {
      expect(() => content({ settings: { audio_volume: value } })).toThrow("audio_volume")
    }
  })

  it("rejects unsupported typed strings without logging their values, including shadowed values", () => {
    for (const value of ['device "quoted"', '"leading', 'a"#unclosed', 'a"b#outside', 'é"x', "a\nb", "a\rb", "a\0b", "a\ud800b", "a\udfffb"]) {
      for (const config of [undefined, { append: 'audio_device = "valid"' }]) {
        expect(() => content({ settings: { audio_device: value }, config }))
          .toThrow(/^Unsupported RetroArch string setting: audio_device$/)
      }
    }
  })

  it("uses the same string safety for baseline directories and autoconfig", () => {
    for (const value of ['root "quoted"', "root\nnext", "root\0next"]) {
      expect(() => launch({ ...input(), accountRoot: value })).toThrow("system_directory")
      expect(() => launch({ ...input(), files: { autoconfig: value } })).toThrow("joypad_autoconfig_dir")
    }
  })
})

// The Nix gate always sets this to a build-machine executable compiled from the
// caller program's patched sources. Standalone TS tests cannot replace that gate.
const parser = process.env.KORRI_TEST_RETROARCH_CONFIG_PARSER
const directory = mkdtempSync(join(tmpdir(), "retroarch-config-"))
afterAll(() => rmSync(directory, { recursive: true, force: true }))
function parsed(cfg: string, keys: string[]): string[] {
  if (!parser) throw new Error("Native parser executable is required")
  const path = join(directory, "retroarch.cfg")
  writeFileSync(path, cfg)
  const result = Bun.spawnSync([parser, path, ...keys])
  expect(result.exitCode).toBe(0)
  return result.stdout.toString().split("\0").slice(0, -1)
}

describe.skipIf(!parser)("pinned config_file_new/config_get_string semantics", () => {
  it("proves the parser keeps the first duplicate and does not JSON-decode strings", () => {
    expect(parsed('video_driver = "gl"\nvideo_driver = "vulkan"\n', ["video_driver"]))
      .toEqual(["gl"])
    expect(parsed(`audio_device = ${JSON.stringify('device "quoted"')}\n`, ["audio_device"]))
      .toEqual(["device \\"])
  })

  it("applies baseline < typed < raw prepend < raw append in native lookups", () => {
    const settings = { video_driver: "vulkan" }
    const prepend = 'video_driver = "ignored"\nvideo_driver = "sdl2"'
    const append = 'video_driver = "glcore"\nvideo_driver = "gl1" # final'
    for (const [overrides, expected] of [
      [undefined, "gl"],
      [{ settings }, "vulkan"],
      [{ settings, config: { prepend } }, "sdl2"],
      [{ settings, config: { prepend, append } }, "gl1"],
      [{ config: { append } }, "gl1"],
    ] as const) {
      expect(parsed(content(overrides), ["video_driver"])).toEqual([expected])
    }
    expect(parsed(content({ settings: { video_vsync: false, audio_volume: -3.5, video_fullscreen: true, audio_latency: 0 } }),
      ["video_vsync", "audio_volume", "video_fullscreen", "audio_latency", "config_save_on_exit", "kiosk_mode_enable", "menu_driver"]))
      .toEqual(["false", "-3.5", "true", "0", "false", "true", "null"])
  })

  it("round-trips native strings, literal backslashes, whitespace, hashes and Unicode", () => {
    for (const value of ["", "device\\path\\n", "\\", " leading\tand trailing ", "a#b", "a=b", "café/🎮", 'hw:"quoted"', 'hw:"dev#1"']) {
      expect(parsed(content({ settings: { audio_device: value } }), ["audio_device"]))
        .toEqual([value])
    }
    const request = input()
    request.accountRoot = "/account\\literal"
    request.files.autoconfig = "/autoconfig\\literal"
    expect(parsed(launch(request).files![0].content, ["system_directory", "joypad_autoconfig_dir"]))
      .toEqual(["/account\\literal/system", "/autoconfig\\literal"])
    expect(parsed(content({ config: { append: 'audio_device = "native\\path#1" # comment' } }), ["audio_device"]))
      .toEqual(["native\\path#1"])
  })
})
