import type {
  PluginLaunchInput,
  PluginLaunchOutput,
} from "../../contracts/generated/korrid"

export const name = "retroarch"
export const title = "RetroArch"
export const description =
  "RetroArch launcher kind and its default Linux build."
export const launchers = {
  retroarch: {
    id: "@korri:retroarch/retroarch",
    kind: "@korri:retroarch/retroarch",
    program: "retroarch",
  },
}
export const sessionControls = {
  openMenu: {
    order: 0,
    id: "@korri:retroarch/open-menu",
    owner: { kind: "launcher", id: "@korri:retroarch/retroarch" },
    label: "Open RetroArch menu",
    interaction: { kind: "command" },
    effect: "@korri:retroarch/open-menu",
    dismissOnSuccess: true,
  },
  quit: {
    order: 1,
    id: "@korri:retroarch/quit",
    owner: { kind: "launcher", id: "@korri:retroarch/retroarch" },
    label: "Quit game",
    interaction: { kind: "command" },
    effect: "@korri:retroarch/quit",
    destructive: true,
    dismissOnSuccess: true,
  },
}

// Legacy setting-policy.ts credential keys plus the approved kiosk protections.
const reservedKeys = [
  "cheevos_password",
  "cheevos_token",
  "network_cmd_password",
  "netplay_password",
  "netplay_spectate_password",
  "kiosk_mode_enable",
  "config_save_on_exit",
  "menu_driver",
]

export function launch(input: PluginLaunchInput): PluginLaunchOutput {
  const root = input.accountRoot
  const states = `${root}/states/${input.runtimeId}`
  const configPath = `${root}/retroarch.cfg`
  const config = input.overrides?.config
  if (config?.replace !== undefined) {
    throw new Error(
      "RetroArch overrides.config does not support replace; use prepend/append",
    )
  }
  // Preserve legacy: both blocks follow Korri's lines; append wins position.
  const raw = [config?.prepend, config?.append]
    .filter((text) => text !== undefined)
    .join("\n")
  const lines: string[] = []
  for (const rawLine of raw.split("\n")) {
    const line = rawLine.trim()
    if (line === "" || line.startsWith("#")) continue
    const separator = line.indexOf("=")
    const key = line.slice(0, separator).trim()
    if (separator < 0 || !/^[A-Za-z0-9_]+$/.test(key)) {
      throw new Error(`Invalid RetroArch overrides.config line: ${line}`)
    }
    if (reservedKeys.includes(key))
      throw new Error(`Reserved RetroArch overrides.config key: ${key}`)
    lines.push(line)
  }
  const quote = (value: string): string => JSON.stringify(value)
  const content = `# generated by Korri
system_directory = ${quote(`${root}/system`)}
savefile_directory = ${quote(`${root}/saves`)}
savestate_directory = ${quote(states)}
screenshot_directory = ${quote(`${root}/screenshots`)}

input_driver = "udev"
input_joypad_driver = "udev"
joypad_autoconfig_dir = ${quote(input.files.autoconfig)}
input_autodetect_enable = "true"
input_max_users = "4"
input_player1_joypad_index = "0"
input_player1_analog_dpad_mode = "1"
# RetroArch value 2 is L3 + R3. Guide remains exclusive to Korri.
input_menu_toggle_gamepad_combo = "2"
# Select + Start exits to Korri (RetroArch 1.22.2 INPUT_COMBO_START_SELECT = 4).
input_quit_gamepad_combo = "4"
quit_press_twice = "false"

kiosk_mode_enable = "true"
menu_driver = "null"
input_overlay_enable = "false"
video_fullscreen = "true"
quit_on_close_content = "true"
config_save_on_exit = "false"
pause_nonactive = "true"
autosave_interval = "10"
savestate_auto_save = "true"
savestate_auto_load = "true"
video_driver = "gl"
${lines.length ? `${lines.join("\n")}\n` : ""}`
  return {
    command: input.program,
    args: ["--config", configPath, "-L", input.runtimePath, input.contentPath],
    directories: [
      `${root}/system`,
      `${root}/saves`,
      states,
      `${root}/screenshots`,
    ],
    files: [{ path: configPath, content }],
    env: {},
    envUnset: [],
  }
}
