#!/usr/bin/env python3
"""Render the Plymouth theme's images and emit the geometry the script needs.

The theme draws two things: one leaf, and five glyphs (k o r r i-stem). Both
are rendered here at a reference size larger than any panel, so the script
only ever scales down — Plymouth's scaler is bilinear, and downscaling is
the only direction that stays clean.

Everything the script needs to place them is measured here and written to
geometry.script, so no coordinate is written twice.

Usage: split-wordmark.py <brand-dir> <out-dir> <resvg>
"""
import os
import re
import subprocess
import sys

BRAND, OUT, RESVG = sys.argv[1], sys.argv[2], sys.argv[3]
WM_REF_W = 1536  # wordmark reference width, px
LEAF_REF_H = 512  # leaf reference height, px
MARGIN = 0.42  # leaf canvas padding, as a fraction of leaf height: Image.Rotate
# keeps the canvas size and clips the corners, so the leaf needs room to turn.

# --- leaf: its own square canvas, with margin for rotation ------------------

mark = open(os.path.join(BRAND, "korri-mark.svg")).read()
inner = re.search(r'<g transform="([^"]+)">(.*)</g>', mark, re.S)
body = inner.group(2)
# Leaf bbox in source units, from build-leaf-mark.py.
LX0, LY0, LX1, LY1 = 0.0, 75.6, 320.0, 423.1
LEAF_H_SRC = LY1 - LY0
PET = (33.0, 423.0)
pad = LEAF_H_SRC * MARGIN
vb = (LX0 - pad, LY0 - pad, (LX1 - LX0) + 2 * pad, LEAF_H_SRC + 2 * pad)
leaf_svg = (
    f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{vb[0]} {vb[1]} {vb[2]} {vb[3]}">'
    f"{body}</svg>"
)
open(f"{OUT}/leaf.svg", "w").write(leaf_svg)
px_per_src = LEAF_REF_H / LEAF_H_SRC
leaf_w = round(vb[2] * px_per_src)
leaf_h = round(vb[3] * px_per_src)
subprocess.run([RESVG, "-w", str(leaf_w), "-h", str(leaf_h), f"{OUT}/leaf.svg", f"{OUT}/leaf.png"], check=True)
os.remove(f"{OUT}/leaf.svg")

leaf = {
    "IMG_W": leaf_w,
    "IMG_H": leaf_h,
    # petiole and leaf-bbox centre, in leaf.png pixels
    "PET_X": (PET[0] - vb[0]) * px_per_src,
    "PET_Y": (PET[1] - vb[1]) * px_per_src,
    "BC_X": ((LX0 + LX1) / 2 - vb[0]) * px_per_src,
    "BC_Y": ((LY0 + LY1) / 2 - vb[1]) * px_per_src,
    "H_PX": LEAF_REF_H,
}

# --- glyphs: one PNG each, all sharing the wordmark canvas ------------------

word = open(os.path.join(BRAND, "korri-wordmark-dark.svg")).read()
wvb = [float(x) for x in re.search(r'viewBox="([^"]+)"', word).group(1).split()]
# Only the letters: everything before the <g> that holds the i-dot leaf.
letters = re.findall(r'<path fill="[^"]+" d="([^"]+)"/>', word.split("<g ")[0])
# Left to right, so the last glyph is the i stem and the snap-in can run
# from the i outwards by walking the list backwards.
letters.sort(key=lambda d: min(float(x) for x in re.findall(r"-?\d+\.?\d*", d)[0::2]))
scale = WM_REF_W / wvb[2]
wm_h = round(wvb[3] * scale)
for i, d in enumerate(letters):
    g = (
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{wvb[0]} {wvb[1]} {wvb[2]} {wvb[3]}">'
        f'<path fill="#FDFDFD" d="{d}"/></svg>'
    )
    open(f"{OUT}/g.svg", "w").write(g)
    subprocess.run([RESVG, "-w", str(WM_REF_W), "-h", str(wm_h), f"{OUT}/g.svg", f"{OUT}/glyph-{i}.png"], check=True)
os.remove(f"{OUT}/g.svg")

# The leaf's placement on the wordmark, mirrored from build-leaf-mark.py.
PETIOLE, I_TOP, GAP, IDOT = (33.0, 423.0), (1250.5, 197.6), 27, 0.34
s = 315 * IDOT / LEAF_H_SRC
idot_leaf_h = LEAF_H_SRC * s  # leaf height in wordmark source units
pet_x = I_TOP[0]
pet_y = I_TOP[1] - GAP

geom = {
    "GLYPHS": len(letters),
    "WM_REF_W": WM_REF_W,
    "WM_REF_H": wm_h,
    # petiole target and leaf height at the i-dot, in wordmark reference px
    "WM_PET_X": (pet_x - wvb[0]) * scale,
    "WM_PET_Y": (pet_y - wvb[1]) * scale,
    "WM_LEAF_H": idot_leaf_h * scale,
    **{f"LEAF_{k}": v for k, v in leaf.items()},
}
with open(f"{OUT}/geometry.script", "w") as f:
    f.write("# Generated by split-wordmark.py — every number is measured, not typed.\n")
    for k, v in geom.items():
        f.write(f"global.{k} = {v:.4f};\n" if isinstance(v, float) else f"global.{k} = {v};\n")
print(f"leaf.png {leaf_w}x{leaf_h}, {len(letters)} glyphs at {WM_REF_W}x{wm_h}")
