use super::{
    AndroidComponent, FileProvisionMode, LaunchContext, LaunchError, LaunchSpec, ProvisionedFile,
};
use crate::config::{resolver::ResolvedRoute, storage, ConfigSnapshot};
use std::{
    collections::HashMap,
    fs::{self, File, OpenOptions},
    io::{Read, Write},
    path::Path,
};

const RETROARCH_PROVIDER: &str = "@korri:retroarch";
const RETROARCH_TOKEN: &str = "retroarch";
fn config_content(root: &Path, libretro_directory: &Path, control_port: u16) -> String {
    format!(
        r#"# generated by Korri
libretro_directory = "{libretro_directory}"
system_directory = "{system}"
savefile_directory = "{saves}"
savestate_directory = "{states}"
screenshot_directory = "{screenshots}"

# Launch-bound authenticated loopback control. A different port is derived
# for every fresh korrid launch identity.
network_cmd_enable = "true"
network_cmd_port = "{control_port}"

# Korri-owned access: RGUI is built in and needs no external asset pack.
# Kiosk remains enabled and every hardware menu shortcut remains disabled.
menu_driver = "rgui"
kiosk_mode_enable = "true"
input_menu_toggle_gamepad_combo = "0"
input_menu_toggle = "nul"
input_overlay_enable = "false"
video_font_enable = "true"

# Korri owns lifecycle and config
quit_on_close_content = "true"
quit_press_twice = "false"
config_save_on_exit = "false"
pause_nonactive = "true"
log_verbosity = "true"

# persistence
savestate_auto_save = "true"
savestate_auto_load = "true"
autosave_interval = "10"

# features retained from stock RetroArch
rewind_enable = "true"
run_ahead_enabled = "true"
run_ahead_frames = "1"
run_ahead_secondary_instance = "true"

# stock Vulkan crashes on Mali/Immortalis
video_driver = "gl"

"#,
        libretro_directory = libretro_directory.display(),
        system = root.join("system").display(),
        saves = root.join("saves").display(),
        states = root.join("states").display(),
        screenshots = root.join("screenshots").display(),
    )
}

fn write_atomically(path: &Path, content: &[u8]) -> std::io::Result<()> {
    let parent = path.parent().ok_or_else(|| {
        std::io::Error::new(std::io::ErrorKind::InvalidInput, "config has no parent")
    })?;
    let file_name = path
        .file_name()
        .and_then(|name| name.to_str())
        .ok_or_else(|| {
            std::io::Error::new(std::io::ErrorKind::InvalidInput, "invalid config name")
        })?;
    let temporary = parent.join(format!(".{file_name}.{:016x}.tmp", rand::random::<u64>()));
    let result = (|| {
        let mut file = OpenOptions::new()
            .write(true)
            .create_new(true)
            .open(&temporary)?;
        file.write_all(content)?;
        file.sync_all()?;
        fs::rename(&temporary, path)?;
        fs::File::open(parent)?.sync_all()?;
        Ok(())
    })();
    if result.is_err() {
        let _ = fs::remove_file(&temporary);
    }
    result
}

pub fn validate_route(route: &ResolvedRoute) -> Result<(), LaunchError> {
    // Membership in the RetroArch family is what admits a route here, never the
    // identity of one runner. Every core in the family reaches this path, so a
    // second core is ordinary rather than a name korrid has to learn.
    if route.provider_id != RETROARCH_PROVIDER
        || route.family_id.as_deref() != Some(RETROARCH_PROVIDER)
        || route.runner_id.is_empty()
        || route.integration_token != RETROARCH_TOKEN
    {
        return Err(LaunchError::RouteUnavailable(format!(
            "route {} is not owned by the RetroArch plugin",
            route.playable_id
        )));
    }
    route.android_component.as_ref().ok_or_else(|| {
        LaunchError::RouteUnavailable(format!(
            "RetroArch route {} has no plugin-provided Android component",
            route.playable_id
        ))
    })?;
    let core = route.core_path.as_ref().ok_or_else(|| {
        LaunchError::RouteUnavailable(format!(
            "RetroArch route {} has no runner-provided core",
            route.playable_id
        ))
    })?;
    if !Path::new(core).is_absolute() {
        return Err(LaunchError::RouteUnavailable(format!(
            "runner {} has a non-absolute Android core path",
            route.runner_id
        )));
    }
    let target = route.file_target.as_ref().ok_or_else(|| {
        LaunchError::RouteUnavailable(format!(
            "RetroArch route {} has no file target",
            route.playable_id
        ))
    })?;
    storage::validate_file_target_shape(target).map_err(|error| {
        LaunchError::RouteUnavailable(format!(
            "RetroArch route {} has invalid file target: {error}",
            route.playable_id
        ))
    })?;
    Ok(())
}

pub fn launch_route(
    root: &Path,
    snapshot: &ConfigSnapshot,
    route: &ResolvedRoute,
    mut context: LaunchContext,
    provision_mode: FileProvisionMode,
    control_port: u16,
) -> Result<LaunchSpec, LaunchError> {
    validate_route(route)?;
    let component = route
        .android_component
        .as_ref()
        .expect("validated component");
    let core = route.core_path.as_ref().expect("validated core");
    let target = route.file_target.as_ref().expect("validated file target");
    let resolved_rom = storage::resolve_file_target(root, snapshot, target).map_err(|error| {
        if error.is_missing_target() {
            LaunchError::RomMissing(error.to_string())
        } else if error.is_storage_access() {
            LaunchError::StorageAccess(error.to_string())
        } else {
            LaunchError::RouteUnavailable(error.to_string())
        }
    })?;
    let rom = resolved_rom.path;
    let mut file =
        File::open(&rom).map_err(|error| LaunchError::StorageAccess(error.to_string()))?;
    let mut hasher = crc32fast::Hasher::new();
    let mut buffer = [0_u8; 64 * 1024];
    loop {
        let length = file
            .read(&mut buffer)
            .map_err(|error| LaunchError::StorageAccess(error.to_string()))?;
        if length == 0 {
            break;
        }
        hasher.update(&buffer[..length]);
    }
    context.content_crc32 = Some(format!("{:08x}", hasher.finalize()));

    let libretro_directory = Path::new(core).parent().ok_or_else(|| {
        LaunchError::RouteUnavailable(format!(
            "runner {} has no containing core directory",
            route.runner_id
        ))
    })?;
    let config = root.join("retroarch.cfg");
    if !(49152..=65535).contains(&control_port) {
        return Err(LaunchError::Config(
            "RetroArch control port is outside the private launch range".into(),
        ));
    }
    let content = config_content(root, libretro_directory, control_port);
    let provisioned_directories = ["system", "saves", "states", "screenshots"];
    let (directories, files) = match provision_mode {
        FileProvisionMode::Direct => {
            for directory in provisioned_directories {
                fs::create_dir_all(root.join(directory))
                    .map_err(|error| LaunchError::Config(error.to_string()))?;
            }
            write_atomically(&config, content.as_bytes())
                .map_err(|error| LaunchError::Config(error.to_string()))?;
            (Vec::new(), Vec::new())
        }
        FileProvisionMode::Deferred => (
            provisioned_directories
                .into_iter()
                .map(|directory| root.join(directory).display().to_string())
                .collect(),
            vec![ProvisionedFile {
                path: config.display().to_string(),
                content,
            }],
        ),
    };

    Ok(LaunchSpec {
        // The RPC preparation boundary replaces this before signing.
        launch_id: String::new(),
        runner_id: route.integration_token.clone(),
        disposition: super::types::LaunchDisposition::Fresh,
        context,
        component: AndroidComponent {
            package_name: component.package_name.clone(),
            class_name: component.class_name.clone(),
        },
        extras: HashMap::from([
            ("ROM".into(), rom.display().to_string()),
            ("LIBRETRO".into(), core.clone()),
            ("CONFIGFILE".into(), config.display().to_string()),
        ]),
        directories,
        files,
        authorized_content_root: Some(resolved_rom.authorized_root.display().to_string()),
        integrity: String::new(),
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    fn root_with_rom() -> tempfile::TempDir {
        let root = tempfile::tempdir().unwrap();
        std::fs::create_dir_all(root.path().join("roms")).unwrap();
        std::fs::write(root.path().join("roms/wl4.gba"), b"123456789").unwrap();
        root
    }

    fn route() -> ResolvedRoute {
        core_route(
            "@korri:mgba/mgba",
            "/data/data/com.korri.retroarch/cores/mgba_libretro_android.so",
        )
    }

    fn core_route(runner_id: &str, core_path: &str) -> ResolvedRoute {
        ResolvedRoute {
            playable_id: "wl4".into(),
            title: Some("Wario Land 4".into()),
            release_id: "gba".into(),
            identity: None,
            provider_id: RETROARCH_PROVIDER.into(),
            system_id: "gba".into(),
            system_title: Some("Game Boy Advance".into()),
            runner_id: runner_id.into(),
            family_id: Some(RETROARCH_PROVIDER.into()),
            integration_token: RETROARCH_TOKEN.into(),
            flattened_target: "roms:wl4.gba".into(),
            android_component: Some(crate::config::resolver::ResolvedAndroidComponent {
                package_name: "com.korri.retroarch".into(),
                class_name: "com.retroarch.browser.retroactivity.RetroActivityFuture".into(),
            }),
            linux_runner: None,
            core_path: Some(core_path.into()),
            file_target: Some(crate::config::resolver::ResolvedFileTarget {
                storage_id: storage::IMPLICIT_ROMS_STORAGE_ID.into(),
                path: "wl4.gba".into(),
            }),
        }
    }

    /// A second core of the RetroArch family must launch exactly like the first.
    /// korrid once compared the runner id against `@korri:mgba/mgba`, so every
    /// other generated core was rejected before it could be listed or launched.
    #[test]
    fn any_core_of_the_retroarch_family_validates() {
        for runner_id in [
            "@korri:mgba/mgba",
            "@korri:snes9x2010/snes9x2010",
            "@alice:ppsspp/ppsspp",
        ] {
            let route = core_route(
                runner_id,
                "/data/data/com.korri.retroarch/cores/any_libretro_android.so",
            );
            validate_route(&route)
                .unwrap_or_else(|error| panic!("{runner_id} should validate: {error}"));
        }
    }

    #[test]
    fn a_route_outside_the_retroarch_family_is_refused() {
        let mut foreign = route();
        foreign.family_id = Some("@alice:ppsspp".into());
        assert!(validate_route(&foreign).is_err());

        let mut nameless = route();
        nameless.runner_id = String::new();
        assert!(validate_route(&nameless).is_err());
    }

    #[test]
    fn launches_wario_land_with_paths_rooted_in_korri_storage() {
        let root = root_with_rom();

        let spec = launch_route(
            root.path(),
            &ConfigSnapshot::default(),
            &route(),
            LaunchContext::unresolved(),
            FileProvisionMode::Direct,
            50000,
        )
        .expect("launch spec");

        assert_eq!(spec.runner_id, "retroarch");
        assert_eq!(spec.component.package_name, "com.korri.retroarch");
        assert_eq!(
            spec.component.class_name,
            "com.retroarch.browser.retroactivity.RetroActivityFuture"
        );
        assert_eq!(
            spec.extras.get("ROM").map(String::as_str),
            Some(root.path().join("roms/wl4.gba").to_str().unwrap())
        );
        assert_eq!(
            spec.extras.get("LIBRETRO").map(String::as_str),
            Some("/data/data/com.korri.retroarch/cores/mgba_libretro_android.so")
        );
        assert_eq!(
            spec.extras.get("CONFIGFILE").map(String::as_str),
            Some(root.path().join("retroarch.cfg").to_str().unwrap())
        );
        assert_eq!(
            spec.authorized_content_root.as_deref(),
            Some(
                root.path()
                    .join("roms")
                    .canonicalize()
                    .unwrap()
                    .to_str()
                    .unwrap()
            )
        );
        assert!(!spec.extras.contains_key("QUITFOCUS"));
        assert_eq!(spec.context.content_crc32.as_deref(), Some("cbf43926"));
        assert!(spec.files.is_empty());
        let config = std::fs::read_to_string(root.path().join("retroarch.cfg")).unwrap();
        assert!(config.contains("video_driver = \"gl\""));
        assert!(config.contains("network_cmd_enable = \"true\""));
        assert!(config.contains("network_cmd_port = \"50000\""));
    }

    #[test]
    fn defers_config_bytes_to_the_android_storage_edge_without_mutating() {
        let root = root_with_rom();
        let config = root.path().join("retroarch.cfg");
        std::fs::write(&config, b"existing config").unwrap();

        let spec = launch_route(
            root.path(),
            &ConfigSnapshot::default(),
            &route(),
            LaunchContext::unresolved(),
            FileProvisionMode::Deferred,
            50000,
        )
        .expect("deferred spec");

        assert_eq!(std::fs::read(&config).unwrap(), b"existing config");
        assert_eq!(
            spec.directories,
            ["system", "saves", "states", "screenshots"].map(|directory| root
                .path()
                .join(directory)
                .display()
                .to_string())
        );
        assert!(spec
            .directories
            .iter()
            .all(|directory| !std::path::Path::new(directory).exists()));
        assert_eq!(spec.files.len(), 1);
        assert_eq!(spec.files[0].path, config.display().to_string());
        assert!(spec.files[0].content.contains("video_driver = \"gl\""));
        assert!(spec.files[0]
            .content
            .contains("kiosk_mode_enable = \"true\""));
    }

    #[cfg(unix)]
    #[test]
    fn direct_provisioning_atomically_replaces_a_config_symlink() {
        use std::os::unix::fs::symlink;

        let root = root_with_rom();
        let outside = root.path().join("outside-user-file");
        std::fs::write(&outside, b"do not replace").unwrap();
        symlink(&outside, root.path().join("retroarch.cfg")).unwrap();

        launch_route(
            root.path(),
            &ConfigSnapshot::default(),
            &route(),
            LaunchContext::unresolved(),
            FileProvisionMode::Direct,
            50000,
        )
        .expect("launch spec");

        assert_eq!(std::fs::read(&outside).unwrap(), b"do not replace");
        assert!(!root.path().join("retroarch.cfg").is_symlink());
        assert!(std::fs::read_to_string(root.path().join("retroarch.cfg"))
            .unwrap()
            .contains("kiosk_mode_enable = \"true\""));
    }

    #[test]
    fn deterministically_provisions_the_kiosk_config_and_save_tree() {
        let root = root_with_rom();
        std::fs::write(root.path().join("retroarch.cfg"), b"user setting").unwrap();

        launch_route(
            root.path(),
            &ConfigSnapshot::default(),
            &route(),
            LaunchContext::unresolved(),
            FileProvisionMode::Direct,
            50000,
        )
        .expect("launch spec");

        let config = std::fs::read_to_string(root.path().join("retroarch.cfg")).unwrap();
        assert!(config.contains("video_driver = \"gl\""));
        assert!(config.contains("menu_driver = \"rgui\""));
        assert!(config.contains("kiosk_mode_enable = \"true\""));
        assert!(config.contains("input_menu_toggle_gamepad_combo = \"0\""));
        assert!(config.contains("input_menu_toggle = \"nul\""));
        assert!(config.contains("autosave_interval = \"10\""));
        assert!(config.contains("log_verbosity = \"true\""));
        assert!(config.contains("quit_press_twice = \"false\""));
        assert!(config.contains(&format!(
            "savefile_directory = \"{}\"",
            root.path().join("saves").display()
        )));
        assert!(!config.contains("QUITFOCUS"));
        for directory in ["system", "saves", "states", "screenshots"] {
            assert!(root.path().join(directory).is_dir(), "missing {directory}");
        }
    }

    #[test]
    fn rejects_missing_rom_and_unsafe_file_targets() {
        let root = tempfile::tempdir().unwrap();
        assert!(matches!(
            launch_route(
                root.path(),
                &ConfigSnapshot::default(),
                &route(),
                LaunchContext::unresolved(),
                FileProvisionMode::Direct,
                50000,
            ),
            Err(LaunchError::RomMissing(_))
        ));

        let mut unsafe_route = route();
        unsafe_route.file_target.as_mut().unwrap().path = "../outside.gba".into();
        assert!(matches!(
            launch_route(
                root.path(),
                &ConfigSnapshot::default(),
                &unsafe_route,
                LaunchContext::unresolved(),
                FileProvisionMode::Direct,
                50000,
            ),
            Err(LaunchError::RouteUnavailable(_))
        ));
    }

    #[cfg(unix)]
    #[test]
    fn distinguishes_unreadable_storage_from_a_missing_rom() {
        use std::os::unix::fs::PermissionsExt;

        let root = root_with_rom();
        std::fs::set_permissions(root.path(), std::fs::Permissions::from_mode(0o000)).unwrap();
        let result = launch_route(
            root.path(),
            &ConfigSnapshot::default(),
            &route(),
            LaunchContext::unresolved(),
            FileProvisionMode::Direct,
            50000,
        );
        std::fs::set_permissions(root.path(), std::fs::Permissions::from_mode(0o700)).unwrap();

        assert!(matches!(result, Err(LaunchError::StorageAccess(_))));
    }
}
