# Turns one catalogue entry into one ordinary plugin package.
#
# The generator writes a plugin.ts and puts the shared RetroArch launch helper
# beside it, then hands that directory to the normal plugin builder. A
# generated plugin passes through the same admission as a hand-written one: it
# has no private interface and receives no extra authority.
{ pkgs, mkPlugin }:
name: spec:
let
  lib = pkgs.lib;
  frontend = import ../retroarch/plugin.nix { inherit pkgs; };

  pluginId = "@korri:${name}";
  runnerId = "${pluginId}/${name}";
  # Attribute names sort, so the rendered file is stable across evaluations.
  systemIds = lib.attrNames spec.systems;

  json = builtins.toJSON;

  systemEntries = lib.concatMapStringsSep "\n" (
    id: "  ${json id}: { id: ${json id}, title: ${json spec.systems.${id}.title} },"
  ) systemIds;

  # One line per claim: the rendered file stays readable in an inspect report.
  discoveryEntries = lib.concatMapStringsSep "\n" (
    id:
    "    ${json "${id}-files"}: { id: ${json "${pluginId}/${id}-files"}, "
    + "title: ${json "${spec.systems.${id}.title} files"}, "
    + "extensions: ${json spec.systems.${id}.extensions}, "
    + "system: ${json id}, runners: [${json runnerId}] },"
  ) systemIds;

  pluginSource = pkgs.writeText "korri-core-plugin-${name}.ts" ''
    // Generated from plugins/libretro/cores.nix. Do not edit this file.
    // Edit the catalogue entry instead, or add a core source beside it.
    export { launch } from "./retroarch"

    export const name = ${json name}
    export const title = ${json spec.title}
    export const description = ${json spec.description}
    export const systems = {
    ${systemEntries}
    }
    export const runners = {
      ${json name}: {
        id: ${json runnerId},
        family: "@korri:retroarch",
        program: "retroarch",
        core: ${json name},
        systems: ${json systemIds},
      },
    }
    export const sessionControls = {
      openMenu: {
        order: 0,
        id: ${json "${pluginId}/open-menu"},
        owner: { kind: "runner", id: ${json runnerId} },
        label: "Open RetroArch menu",
        interaction: { kind: "command" },
        effect: "@korri:retroarch/open-menu",
        dismissOnSuccess: true,
      },
      quit: {
        order: 1,
        id: ${json "${pluginId}/quit"},
        owner: { kind: "runner", id: ${json runnerId} },
        label: "Quit game",
        interaction: { kind: "command" },
        effect: "@korri:retroarch/quit",
        destructive: true,
        dismissOnSuccess: true,
      },
    }
    export const discovery = {
      fileReleases: {
    ${discoveryEntries}
      },
    }
  '';

  # Regular files, never symlinks: the builder refuses a symlinked source.
  source = pkgs.runCommand "korri-core-source-${name}" { } ''
    mkdir -p "$out"
    cp ${./retroarch.ts} "$out/retroarch.ts"
    cp ${pluginSource} "$out/plugin.ts"
    chmod u+w "$out/retroarch.ts" "$out/plugin.ts"
  '';
in
# The package is what a device installs. The source is exposed beside it so
# checks and fixtures can read the exact generated text.
(mkPlugin {
  publisher.namespace = "@korri";
  inherit source;
  # The runner carries its own frontend and its own core. Two cores installed
  # together share one RetroArch store path; they never share a dependency the
  # player can remove.
  plugin =
    { pkgs }:
    {
      packages = frontend.packages // {
        ${name} = spec.core;
      };
      files = frontend.files // {
        ${name} = spec.coreFile;
      };
    };
}).overrideAttrs
  (old: {
    passthru = (old.passthru or { }) // {
      inherit source;
      generatedPlugin = pluginSource;
    };
  })
