"""Check the actual config generated by NixOS configSectionsToConfFile."""

import json
from pathlib import Path
import re
import sys

# The pinned NixOS WirePlumber module serializes each native section as
# 'section = JSON'. Require exactly the intended output-only priority rule.
section, content = Path(sys.argv[1]).read_text().split(" = ", 1)
assert section == "monitor.alsa.rules"
rules = json.loads(content)
assert len(rules) == 1
rule = rules[0]
assert set(rule) == {"matches", "actions"}
assert rule["actions"] == {"update-props": {"priority.session": 1100}}
assert len(rule["matches"]) == 1
match = rule["matches"][0]
assert set(match) == {"node.name"}
pattern = match["node.name"]
assert pattern.startswith("~")
# Speaker, HDMI and microphone names come from the live PipeWire inventory.
assert re.fullmatch(pattern[1:], "alsa_output.platform-sound.HiFi__Speaker__sink")
# PipeWire derives this sibling name from the same UCM card's Headphones device.
assert re.fullmatch(pattern[1:], "alsa_output.platform-sound.HiFi__Headphones__sink")
assert not re.fullmatch(pattern[1:], "alsa_output.platform-hdmi-sound.stereo-fallback")
assert not re.fullmatch(pattern[1:], "alsa_input.platform-sound.HiFi__Mic__source")
print(
    "Verified generated onboard-output priority policy; no microphone, volume or HDMI changes"
)
