/**
 * Pico's faces, as data. Generated by scripts/build-fonts.py from
 * src/fonts/; do not edit.
 */
export const PICO_FONT_IDS = [
  "tiny5",
  "tom-thumb",
  "x11-4x6",
  "kenney-mini",
  "m3x6",
  "x11-5x7",
  "spleen-5x8",
  "m5x7",
  "monogram",
  "kenney-pixel",
] as const

export type PicoFontId = (typeof PICO_FONT_IDS)[number]

export interface PicoFont {
  readonly id: PicoFontId
  readonly name: string
  /** The CSS family pico-fonts.css declares for it. */
  readonly family: string
  /** Glyph pixels in one em: ascent plus descent. Type sizes are whole multiples. */
  readonly rows: number
  /** Glyph pixels from the baseline to the top of an H, and of an x. */
  readonly capHeight: number
  readonly xHeight: number
  readonly by: string
  readonly license: string
  /** The licence text shipped in src/fonts/licenses/, when the licence asks for it. */
  readonly licenseFile?: string
}

export const PICO_FONTS: readonly PicoFont[] = [
  {
    id: "tiny5",
    name: "Tiny5",
    family: "Pico Tiny5",
    rows: 7,
    capHeight: 5,
    xHeight: 4,
    by: "The Tiny5 Project Authors (Gissio)",
    license: "SIL Open Font License 1.1",
    licenseFile: "tiny5-OFL.txt",
  },
  {
    id: "tom-thumb",
    name: "Tom Thumb",
    family: "Pico Tom Thumb",
    rows: 6,
    capHeight: 5,
    xHeight: 4,
    by: "Brian Swetland and Robey Pointer",
    license: "CC0 1.0 (also offered under MIT and CC BY 3.0)",
  },
  {
    id: "x11-4x6",
    name: "X11 fixed 4x6",
    family: "Pico X11 fixed 4x6",
    rows: 6,
    capHeight: 5,
    xHeight: 4,
    by: "the X Consortium fixed fonts",
    license: "Public domain",
  },
  {
    id: "kenney-mini",
    name: "Kenney Mini",
    family: "Pico Kenney Mini",
    rows: 7,
    capHeight: 5,
    xHeight: 4,
    by: "Kenney (www.kenney.nl)",
    license: "CC0 1.0",
  },
  {
    id: "m3x6",
    name: "m3x6",
    family: "Pico m3x6",
    rows: 8,
    capHeight: 6,
    xHeight: 5,
    by: "Daniel Linssen",
    license: "Free to use with attribution",
  },
  {
    id: "x11-5x7",
    name: "X11 fixed 5x7",
    family: "Pico X11 fixed 5x7",
    rows: 7,
    capHeight: 6,
    xHeight: 4,
    by: "the X Consortium fixed fonts",
    license: "Public domain",
  },
  {
    id: "spleen-5x8",
    name: "Spleen 5x8",
    family: "Pico Spleen 5x8",
    rows: 8,
    capHeight: 6,
    xHeight: 5,
    by: "Frederic Cambus",
    license: "BSD 2-Clause",
    licenseFile: "spleen-LICENSE.txt",
  },
  {
    id: "m5x7",
    name: "m5x7",
    family: "Pico m5x7",
    rows: 9,
    capHeight: 7,
    xHeight: 5,
    by: "Daniel Linssen",
    license: "CC0 1.0 (attribution appreciated)",
  },
  {
    id: "monogram",
    name: "monogram",
    family: "Pico monogram",
    rows: 9,
    capHeight: 7,
    xHeight: 5,
    by: "datagoblin",
    license: "CC0 1.0",
  },
  {
    id: "kenney-pixel",
    name: "Kenney Pixel",
    family: "Pico Kenney Pixel",
    rows: 9,
    capHeight: 7,
    xHeight: 6,
    by: "Kenney (www.kenney.nl)",
    license: "CC0 1.0",
  },
]

/** The face Pico uses when its root names none. */
export const PICO_DEFAULT_FONT: PicoFontId = "tiny5"
